# Generated by Django 2.1.2 on 2018-10-12 17:02

from django.conf import settings
from django.db import migrations, models
import study.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Syllabus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200)),
                ('number_for_subject', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=models.SET(study.models.get_sentinel_user), to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=models.SET(study.models.get_sentinel_user), related_name='updated_syllabus_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
