# Generated by Django 2.1.2 on 2018-10-23 15:55

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import study.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_name', models.CharField(max_length=200, unique=True)),
                ('number_for_subject', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=models.SET(study.models.get_sentinel_user), to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reading_name', models.CharField(max_length=300, unique=True)),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=models.SET(study.models.get_sentinel_user), to=settings.AUTH_USER_MODEL)),
                ('reading_for', models.ForeignKey(on_delete=models.SET(study.models.get_sentinel_user), related_name='lessons', to='study.Lesson')),
            ],
        ),
        migrations.CreateModel(
            name='Syllabus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200, unique=True)),
                ('number_for_subject', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=models.SET(study.models.get_sentinel_user), to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=models.SET(study.models.get_sentinel_user), related_name='updated_syllabus_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='reading',
            name='reading_for_subject',
            field=models.ForeignKey(on_delete=models.SET(study.models.get_sentinel_user), related_name='readings', to='study.Syllabus'),
        ),
        migrations.AddField(
            model_name='reading',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET(study.models.get_sentinel_user), related_name='updated_reading_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lesson',
            name='lesson_for',
            field=models.ForeignKey(on_delete=models.SET(study.models.get_sentinel_user), related_name='subject_list', to='study.Syllabus'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET(study.models.get_sentinel_user), related_name='updated_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
