# Generated by Django 2.1.2 on 2018-10-12 18:34

from django.conf import settings
from django.db import migrations, models
import study.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('study', '0002_auto_20181012_1720'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_name', models.CharField(max_length=200, unique=True)),
                ('number_for_subject', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=models.SET(study.models.get_sentinel_user), to=settings.AUTH_USER_MODEL)),
                ('lesson_for', models.ForeignKey(on_delete=models.SET(study.models.get_sentinel_user), related_name='belongs_to_subject', to='study.Syllabus')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=models.SET(study.models.get_sentinel_user), related_name='updated_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
