# Generated by Django 2.1.2 on 2018-10-13 08:52

from django.db import migrations, models
import study.models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0004_reading'),
    ]

    operations = [
        migrations.AddField(
            model_name='reading',
            name='reading_for_subject',
            field=models.ForeignKey(default='', on_delete=models.SET(study.models.get_sentinel_user), related_name='belongs_to_reading', to='study.Syllabus'),
            preserve_default=False,
        ),
    ]
