# Generated by Django 2.1.2 on 2018-10-20 16:17

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0005_reading_reading_for_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reading',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
